name: Deploy for EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on AWS EC2
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Config SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
      - name: Copy files
        run: |
          rsync -avz --delete -e "ssh -o -o StrictHostKeyChecking=no -i private_key.pem " ./ ubuntu@3.143.216.45:/home/ubuntu/www/

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@3.143.216.45 << 'EOF'
            cd /home/ubuntu/www 
            composer install --no-dev --optimize-autoloader 
            systemctl restart apache2
            echo "Finished"
          EOF